name: scouting_app_2024
description: "Rebel Robotics FRC 2638 Scouting App 2024"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_storage: ^2.1.1
  logging: ^1.2.0
  responsive_grid_list: ^1.4.0
  theme_provider: ^0.6.0
  url_launcher: ^6.2.3
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/crescendo/field.png
    - assets/crescendo/high_note.png
    - assets/crescendo/note.png
    - assets/appicon_header.png
  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
          weight: 100
          style: italic
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/mono/IBMPlexMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/mono/IBMPlexMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/mono/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/mono/IBMPlexMono-Italic.ttf
          weight: 400
          style: italic
